# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Riverrun46
tagline:             'Yet Another Personal Blog'
description:         'Yep. Post fun stuff randomly.'
url:                 'https://riverrun46.github.io'
baseurl:             'https://riverrun46.github.io'
paginate:            5

# About/contact
author:
  name:              Ivan Tse
  url:               https://github.com/riverrun46/
  email:             river_run@126.com

# Custom vars
version:             1.0.0
